In [1]:
import numpy as np

# Prosjekt 2

## Task 1

In [2]:
###a)
# Definerer matrisa
A1 = np.array([[1000,1],[0,1],[0,0]])

# Kalkulerer SVD med hjelp av innebygd numpy funksjon
U,S,Vt = np.linalg.svd(A1, full_matrices = False)

# Skriver ut resultatene 
print("U:")
print(U)
print("S:")
print(S)
print("Vt:")
print(Vt)

# Tester om det blir likt, ved å bruke hintet for å gange de sammen
H = U*S
A_tilbake = np.around(H@Vt)
print("A1:")
print(A_tilbake)

U:
[[ 1.e+00 -1.e-06]
 [ 1.e-06  1.e+00]
 [ 0.e+00  0.e+00]]
S:
[1.0000005e+03 9.9999950e-01]
Vt:
[[ 0.9999995  0.001    ]
 [-0.001      0.9999995]]
A1:
[[1000.    1.]
 [  -0.    1.]
 [   0.    0.]]


Ved observasjon av av sigma, ser man at A har egenverdiene 1000, og 1. 
Derfor ser vi på egenvektorene korresponderende til den største egenverdien.
Dette blir nemlig U_1, altså egenvektoren [1,1*10^-6,0]^T, siden denne forteller
mest om A. 

In [17]:
###b)
A2 = np.array([[1,0,0],[1,0,0],[0,0,1]])
U,S,Vt = np.linalg.svd(A2, full_matrices = False)
def trunkSVD(U,S,Vt,d):
    d+=-1
    W=U[:,:d]
    Vt=Vt[:d,:]
    S=np.diag(S[:d])
    H=S@Vt
    return(W,H)
W_2,H=(trunkSVD(U,S,Vt,d=3))
print(W_2 @ H)


[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


Siden vi bruker full_matrices = false, inkluderer ikke matrisen urelevant informasjon, den vil redusere matrisen slik at vi kun får relevant informasjon, eller nærmere bestemt, den mest relevante informasjonen. 
Hele poenget med trunk er å fokusere på den viktigste informasjonen, men i gjengjeld vil du miste de minste veridene og i A2 vil vi miste noen deler, siden alle verdiene er like. Trink prøver å bevare så mye så muligt, men siden den vektlegger alle veridnee likt, vil den noen verdier gå tapt. 
All informasjon i matrisen U vil være nyttige til å rekonstruere A, som betyr at ingen av kollonnene i A_2 er lineart avhengig av de andre. 

In [18]:
###c)
def orthproj(W, B):
    # Kalkulerer projeksjonsmatrisen
    P = W@W.T
    # Projekterer kolonnene i B inn på "ordboken" W
    PB = P@B
    return PB